automation:
  image: debian:stable-slim
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends \
        git make openssh-client ca-certificates curl findutils jq squashfs-toolsxz-utils
  script:
    - ./automation.sh

